// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a ModelGenerator.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace BroadCapture.Models
{
    //You can get Utilities package via nuget : Install-Package Deszolate.Utilities.Lite
    //[Utilities.Attributes.SQL.Table("Message")]
    public partial class Message
    {
        public long id { get; set; }
        public string content { get; set; }
        public int? type { get; set; }
        public DateTime? createdate { get; set; }
        public string createby { get; set; }
        public bool issell { get; set; }
        public bool isbuy { get; set; }
        public bool istrade { get; set; }
    }
}

