// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace BroadCaptureML.Model
{
    public class ModelInput
    {
        [ColumnName("Content"), LoadColumn(0)]
        public string Content { get; set; }


        [ColumnName("Type"), LoadColumn(1)]
        public string Type { get; set; }


        [ColumnName("CreateDate"), LoadColumn(2)]
        public string CreateDate { get; set; }


        [ColumnName("CreateBy"), LoadColumn(3)]
        public float CreateBy { get; set; }


        [ColumnName("Id"), LoadColumn(4)]
        public float Id { get; set; }


    }
}
